// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn5uG1iMTQFpo5vw9SBnYCWYa1j6h6B1c',
    appId: '1:956772603917:web:324bbc2bc3bce11e361d44',
    messagingSenderId: '956772603917',
    projectId: 'freelance-88349',
    authDomain: 'freelance-88349.firebaseapp.com',
    storageBucket: 'freelance-88349.appspot.com',
    measurementId: 'G-L4SJ2JTT8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvagSqxuaxfJ5gssSWZ7xZibBIbVbeMhc',
    appId: '1:956772603917:android:452fd6849e506515361d44',
    messagingSenderId: '956772603917',
    projectId: 'freelance-88349',
    storageBucket: 'freelance-88349.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD5sAua3r5US5hlm-Un4H97xYXz9msX6o',
    appId: '1:956772603917:ios:0a4d686d726ae3a6361d44',
    messagingSenderId: '956772603917',
    projectId: 'freelance-88349',
    storageBucket: 'freelance-88349.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD5sAua3r5US5hlm-Un4H97xYXz9msX6o',
    appId: '1:956772603917:ios:0a4d686d726ae3a6361d44',
    messagingSenderId: '956772603917',
    projectId: 'freelance-88349',
    storageBucket: 'freelance-88349.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn5uG1iMTQFpo5vw9SBnYCWYa1j6h6B1c',
    appId: '1:956772603917:web:a85c2cc4849a62d5361d44',
    messagingSenderId: '956772603917',
    projectId: 'freelance-88349',
    authDomain: 'freelance-88349.firebaseapp.com',
    storageBucket: 'freelance-88349.appspot.com',
    measurementId: 'G-6ZXX7C7GYN',
  );
}
